export const en = {
  filter_playlists: 'Filter Playlists...',
  filter_videos: 'Filter Videos...',
  filter_items: 'Filter Items...',
  videos: 'Videos',
  playlists: 'Playlists',
  channels: 'Channels',
  subscriptions: 'Subscriptions',
  type_video: 'Video',
  type_playlist: 'Playlist',
  type_channel: 'Channel',
  short_video: 'Short Video',
  show_more: 'SHOW MORE',
  show_less: 'SHOW LESS',
  video_long: 'Over 20 Minutes',
  video_medium: '4-20 Minutes',
  video_short: 'Below 4 Minutes',
};
